name: FrontEnd-CI-CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
      - name: pull code
        uses: actions/checkout@v2

      - name: install node
        run: echo "install node"
        shell: bash
        
      - name: install npm modules
        run: echo "install npm modules"
        shell: bash
        
      - name: build node app
        run: echo "build node app"
        shell: bash

      - name: publish files       # store publish files in shared path
        run: echo "publish files"
        shell: bash

  deployment:
    runs-on: ubuntu-latest       # should be front end server in aws
    steps:
      - name: stop nginx service
        run: echo "stop nginx service"
        shell: bash
        
      - name: copy/replace publish files
        run: echo "copy/replace publish files"
        shell: bash

      - name: start nginx service
        run: echo "start nginx service"
        shell: bash
